"""Writing the snapshot as one workbook, to upload to Google Sheets in one step.

Building the Sheet by hand means creating eight tabs, naming each one exactly right
and pasting eight CSVs into them. That is tedious and it is also the step most likely
to go wrong: a paste that lands one column over is the failure this whole package
exists to catch, and it is nicer not to invite it.

So: one file, eight correctly named tabs, a frozen header row, sensible column widths,
and a dropdown on every column that has a controlled vocabulary. Upload it, open it as
a Google Sheet, and `personas pull` can read it straight back.

openpyxl is an optional extra (`uv sync --extra sheet`), because nothing else in this
package needs it and the generator itself stays dependency-light.
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

from .tables import TABS
from .validate import VOCAB_OF

#: A helper tab holding one column per vocabulary, because a dropdown needs a
#: contiguous range and the Enums tab is long format. `pull` ignores it: it only
#: fetches the eight declared tabs.
LISTS = "Lists"

HEADER_FILL = "FFEDF1F5"
HEADER_FONT = "FF16303F"

NOTE = (
    "Generated by `personas init-sheet`. Upload this file to Google Drive, open it "
    "with Google Sheets, then share it so anyone with the link can view and run "
    "`personas pull --sheet-url <the sheet's URL>`. Extra tabs are ignored; the eight "
    "named tabs are the ones read."
)


def _require_openpyxl():
    try:
        import openpyxl  # noqa: F401
    except ImportError as e:  # pragma: no cover - exercised by hand, not in CI
        raise RuntimeError(
            "init-sheet needs openpyxl, which is an optional extra so that the "
            "generator itself stays dependency-light.\n"
            "  uv sync --extra sheet        (or: uv pip install openpyxl)"
        ) from e
    return openpyxl


def _read(path: Path) -> tuple[list[str], list[list[str]]]:
    with path.open(encoding="utf-8-sig", newline="") as f:
        rows = list(csv.reader(f))
    if not rows:
        return [], []
    header = [h.strip() for h in rows[0]]
    while header and not header[-1]:
        header.pop()
    return header, rows[1:]


def _vocabularies(header: list[str], rows: list[list[str]]) -> dict[str, list[str]]:
    """The Enums tab, pivoted into one list per vocabulary."""
    idx = {h: i for i, h in enumerate(header)}
    out: dict[str, list[tuple[float, str]]] = {}
    for r in rows:
        def cell(name: str) -> str:
            i = idx.get(name, -1)
            return r[i].strip() if 0 <= i < len(r) else ""
        vocab, value = cell("vocab"), cell("value")
        if not vocab or not value:
            continue
        try:
            order = float(cell("sort_order") or 1e9)
        except ValueError:
            order = 1e9
        out.setdefault(vocab, []).append((order, value))
    return {k: [v for _, v in sorted(vs)] for k, vs in sorted(out.items())}


def _width(header: str, values: list[str]) -> float:
    longest = max([len(header)] + [len(v) for v in values[:400]] or [0])
    return min(max(longest + 2, 9), 46)


def write_workbook(data_dir: Path, out_file: Path) -> Path:
    """One workbook from a snapshot directory."""
    openpyxl = _require_openpyxl()
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter
    from openpyxl.worksheet.datavalidation import DataValidation

    data_dir, out_file = Path(data_dir), Path(out_file)
    wb = openpyxl.Workbook()
    wb.remove(wb.active)

    head_fill = PatternFill("solid", fgColor=HEADER_FILL)
    head_font = Font(bold=True, color=HEADER_FONT)
    wrap = Alignment(vertical="top", wrap_text=False)

    tables: dict[str, tuple[list[str], list[list[str]]]] = {}
    for name in TABS:
        path = data_dir / f"{name}.csv"
        if not path.exists():
            raise FileNotFoundError(
                f"{path} not found. Run `personas init-data` first, or point "
                f"--data at a snapshot directory."
            )
        tables[name] = _read(path)

    enums_header, enums_rows = tables["enums"]
    vocabs = _vocabularies(enums_header, enums_rows)

    for name in TABS:
        header, rows = tables[name]
        ws = wb.create_sheet(name.capitalize())
        ws.append(header)
        for r in rows:
            ws.append(r[:len(header)] + [""] * max(0, len(header) - len(r)))
        for i, h in enumerate(header, start=1):
            c = ws.cell(row=1, column=i)
            c.fill, c.font, c.alignment = head_fill, head_font, wrap
            col = [r[i - 1] if i - 1 < len(r) else "" for r in rows]
            ws.column_dimensions[get_column_letter(i)].width = _width(h, col)
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = (
            f"A1:{get_column_letter(max(len(header), 1))}{len(rows) + 1}")

    # The helper tab the dropdowns point at.
    lists = wb.create_sheet(LISTS)
    lists.append(list(vocabs))
    for i, (vocab, values) in enumerate(vocabs.items(), start=1):
        lists.cell(row=1, column=i).font = head_font
        lists.cell(row=1, column=i).fill = head_fill
        for j, v in enumerate(values, start=2):
            lists.cell(row=j, column=i, value=v)
        lists.column_dimensions[get_column_letter(i)].width = _width(vocab, values)
    lists.freeze_panes = "A2"
    lists["A1"].comment = None

    col_of_vocab = {v: get_column_letter(i)
                    for i, v in enumerate(vocabs, start=1)}

    # A dropdown on every column with a controlled vocabulary.
    added = 0
    for (tab, column), vocab in sorted(VOCAB_OF.items()):
        if tab not in tables or vocab not in vocabs:
            continue
        header, rows = tables[tab]
        if column not in header:
            continue
        ws = wb[tab.capitalize()]
        letter = get_column_letter(header.index(column) + 1)
        vcol = col_of_vocab[vocab]
        last = len(vocabs[vocab]) + 1
        dv = DataValidation(
            type="list",
            formula1=f"={LISTS}!${vcol}$2:${vcol}${last}",
            allow_blank=True,
            showErrorMessage=True,
        )
        dv.errorTitle = f"Not a {vocab}"
        dv.error = (f"{column} must be one of the {vocab} values on the {LISTS} tab. "
                    f"Add a row to Enums first if you need a new one.")
        ws.add_data_validation(dv)
        dv.add(f"{letter}2:{letter}{max(len(rows) + 200, 400)}")
        added += 1

    readme = wb.create_sheet("READ ME", 0)
    readme.column_dimensions["A"].width = 104
    readme["A1"] = "Egress Persona Model"
    readme["A1"].font = Font(bold=True, size=14)
    readme["A3"] = NOTE
    readme["A3"].alignment = Alignment(wrap_text=True, vertical="top")
    readme.row_dimensions[3].height = 64
    readme["A5"] = "Tabs read by the generator"
    readme["A5"].font = Font(bold=True)
    row = 6
    for name, spec in TABS.items():
        readme.cell(row=row, column=1,
                    value=f"{name.capitalize():<12} {len(spec.columns)} columns, "
                          f"keyed by {spec.key or '(no key)'}")
        row += 1
    readme.cell(row=row + 1, column=1,
                value=f"{LISTS:<12} a helper tab the dropdowns point at. Not read.")
    readme.cell(row=row + 3, column=1,
                value="Blank always means 'not stated' — never zero, never false.")
    readme.cell(row=row + 4, column=1,
                value="An undeclared column is an error, not a column the generator "
                      "quietly ignores.")
    readme.cell(row=row + 5, column=1,
                value="Run `personas validate` after editing; it names the cell.")

    out_file.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out_file)
    return out_file


def describe(data_dir: Path) -> dict[str, Any]:
    """What the workbook will contain, for the command's own output."""
    out: dict[str, Any] = {"tabs": {}, "dropdowns": 0}
    for name in TABS:
        path = Path(data_dir) / f"{name}.csv"
        if path.exists():
            header, rows = _read(path)
            out["tabs"][name.capitalize()] = (len(rows), len(header))
    enums = Path(data_dir) / "enums.csv"
    if enums.exists():
        h, r = _read(enums)
        vocabs = _vocabularies(h, r)
        out["vocabs"] = len(vocabs)
        out["dropdowns"] = sum(
            1 for (tab, col), v in VOCAB_OF.items()
            if v in vocabs and tab in TABS
            and col in _read(Path(data_dir) / f"{tab}.csv")[0]
        )
    return out
